### ISSUE TITLE
Issue 6: For Milestone 3 Training the Model

### ISSUE THREAD

**Issue by Josh-chief** [Josh-chief/TEAM-C.I-Rash-Hour#5]
- [x] Data Splitting 
- [x] Bootstrapping 
- [x] Cross Validation (basic, repeated or LOOCV)
- [x] Model Training for Either Classification, Regression Association or Clustering (as applicable 
- [ ] Model Performance Comparison Using Resample (for classification and regression)

**Comment by Josh-chief** [comment]
6th issue done
